export const slides = [
 {id:'cover',section:'Safety Monitoring',title:'A clearer view of\nthe workplace.',type:'cover',notes:'Introduce the official study title: IoT-Based Workplace Environmental Hazard Monitoring and Early Warning System Using ESP32 and Blynk. Explain that this is an educational prototype. The presentation is followed by a demonstration of the actual hardware.',source:'IMRAD cover, abstract'},
 {id:'problem',section:'Introduction',title:'One workplace.\nSeveral changing conditions.',type:'problem',notes:'Explain the need for continuous environmental monitoring. Manual checks and isolated alarms may not provide continuous remote visibility. Our scope covers ambient temperature, humidity, relative sound amplitude and relative MQ-135 response.',source:'IMRAD pp. 3–4'},
 {id:'objectives',section:'Introduction',title:'What the study sets out to do',type:'objectives',notes:'The general objective is to design, build and functionally evaluate a low-cost workplace monitoring and early-warning prototype. Summarize the five objectives without reading each line verbatim.',source:'IMRAD pp. 3–4'},
 {id:'architecture',section:'Methodology',title:'Decisions happen on the ESP32.',type:'architecture',notes:'Describe the path from sensor acquisition through validated states to risk assessment and warning outputs. Blynk is a supplementary monitoring layer. Wi-Fi failure does not stop local sensing or warning logic.',source:'IMRAD pp. 4–5, 9–10'},
 {id:'processing',section:'Methodology',title:'A single spike is not enough.',type:'processing',notes:'DHT11 uses two valid readings and separate entry/exit thresholds. MAX4466 uses quiet-floor calibration, median filtering and persistence. MQ-135 uses a reference ratio, confirmation and event-recovery logic. Explain the processing approach without discussing individual GPIO pins.',source:'IMRAD pp. 6–8'},
 {id:'risk',section:'Methodology',title:'Five levels of warning',type:'risk',notes:'LEDs illuminate cumulatively. The algorithm considers confirmed severity and the number of major hazards. Level 4 includes two major hazards or specific severe conditions. Level 5 includes critical temperature, critical MQ response or at least three major hazards. The buzzer has a separate alarm rule.',source:'IMRAD p. 9, Table 6'},
 {id:'normal',section:'Results',title:'The normal run stayed at SAFE.',type:'normal',notes:'These values are a representative recorded run from the IMRAD, not live readings. Temperature was around 26.5 °C, humidity around 51%, MQ ratio around 1.00, score zero and risk Level 1. Noise was normal, the buzzer was off and only LED 1 was on.',source:'IMRAD p. 12, Table 9'},
 {id:'tests',section:'Results',title:'The prototype responded to\npersistent and combined conditions.',type:'tests',notes:'Brief sound stayed transient. Sustained noise progressed to HIGH or VERY HIGH. Humidity of about 89–91% reached VERY HIGH. The combined run reached score about 6, two major hazards, Level 4, four LEDs and an active alarm. The source reports functional observations, not response-rate percentages.',source:'IMRAD pp. 14–16'},
 {id:'recovery',section:'Results & Discussion',title:'The MQ-135 revealed\na recovery problem.',type:'recovery',notes:'The strong disturbance example used sensitive V4.1.5 settings, not the final V4.1.6 thresholds. The signal initially recovered but later rebounded. V4.1.6 adds event-peak tracking and controlled reference recovery. The IMRAD still recommends a final regression test of that sequence.',source:'IMRAD pp. 12–13, 16–17'},
 {id:'cloud',section:'Results',title:'Remote visibility through Blynk',type:'cloud',notes:'This is the actual Figure 2 dashboard screenshot in the supplied IMRAD. It is a separate snapshot, not the normal-state run. Logs recorded successful Wi-Fi and Blynk ONLINE states. V0 is ambient temperature although the screenshot widget says CPU Temperature. Do not present this screenshot as a validation trace of final firmware classification.',source:'IMRAD pp. 14–15, Figure 2'},
 {id:'limits',section:'Discussion',title:'Functional evidence.\nA defined scope.',type:'limits',notes:'The tests show system behavior, not certified occupational measurement accuracy. MAX4466 values are not decibels. MQ-135 is not a ppm, gas-identification or official AQI instrument. A short demonstration warm-up is different from formal manufacturer preheating. Final V4.1.6 recovery still needs a regression check.',source:'IMRAD pp. 11, 16–17'},
 {id:'conclusion',section:'Conclusion',title:'Environmental monitoring,\nwith local early warnings.',type:'conclusion',notes:'Conclude that the prototype integrates sensing, rule-based assessment, progressive warnings and remote monitoring within the educational scope. Transition to the real project demonstration. Advance to the Live Demonstration slide and show the actual hardware and Blynk dashboard.',source:'IMRAD pp. 17–18'},
 {id:'demonstration',section:'Live Demonstration',title:'The actual project.\nIn action.',type:'demonstration',notes:'We will now demonstrate the actual project.',source:'Live project demonstration'}
];

export const references = [
 {author:'Espressif Systems',title:'ESP32-WROOM-32 Datasheet',detail:'ver. 3.7, 2026',url:'https://documentation.espressif.com/esp32-wroom-32_datasheet_en.html'},
 {author:'Blynk',title:'Virtual Pin',publication:'Blynk Documentation',url:'https://docs.blynk.io/en/blynk.console/templates/datastreams/virtual-pin'},
 {author:'Blynk',title:'Timers',publication:'Blynk Documentation',url:'https://docs.blynk.io/en/blynk-library-firmware-api/blynk-timer'},
 {author:'Zhengzhou Winsen Electronics Technology Co., Ltd.',title:'MQ135 Air Quality Gas Sensor Manual',detail:'ver. 1.6, 2021',url:'https://www.winsen-sensor.com/d/files/manual/mq135.pdf'},
 {author:'B. Earl',title:'Adafruit Microphone Amplifier Breakout',publication:'Adafruit Learning System',detail:'updated 2024',url:'https://learn.adafruit.com/adafruit-microphone-amplifier-breakout/overview'}
];
