import React, {useState,useEffect,useRef} from 'react';
import {createRoot} from 'react-dom/client';
import {slides,references} from './content';
import dashboard from './blynk.png';
import './style.css';
const pad=n=>String(n).padStart(2,'0');
function Icon({name,...props}){const paths={next:'m9 5 7 7-7 7',prev:'m15 5-7 7 7 7',full:'M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5',grid:'M3 3h6v6H3zM15 3h6v6h-6zM3 15h6v6H3zM15 15h6v6h-6z',close:'m6 6 12 12M6 18 18 6',note:'M5 3h14v18H5zM8 8h8M8 12h8M8 16h5',check:'m5 12 4 4L19 6',play:'m8 4 12 8-12 8z'};return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true" {...props}><path d={paths[name]||paths.next}/></svg>}
function SignalDiagram(){return <div className="signal-diagram" aria-label="Three sensors feed the ESP32, which controls local warnings and reports to Blynk"><div className="sensor-list">{[['DHT11','Temperature + humidity'],['MAX4466','Relative sound'],['MQ-135','Relative air response']].map(([n,t],i)=><div className="sensor" style={{'--i':i}} key={n}><span className="signal-dot"/><b>{n}</b><small>{t}</small></div>)}</div><div className="flow-line"/><div className="processor"><span>LOCAL PROCESSING</span><strong>ESP32</strong><small>Sense · assess · warn</small></div><div className="flow-line second"/><div className="outputs"><div><b>LEDs + buzzer</b><small>Local warnings</small></div><div><b>Blynk</b><small>Remote visibility</small></div></div></div>}
function SlideContent({slide,onDemo}){switch(slide.type){
case 'cover':return <div className="cover-layout"><div><p className="lead">IoT-Based Workplace Environmental Hazard Monitoring and Early Warning System Using ESP32 and Blynk</p><p className="authors">Lycos B. Blanza · Nino Casanova<br/>Justin Chase Guirre · Francis Medrano</p><p className="small-meta">IoT Project Development / Firmware V4.1.6</p></div><div className="cover-visual"><SignalDiagram/></div></div>;
case 'problem':return <><div className="four-words">{['Temperature','Humidity','Sound','Air response'].map((x,i)=><div className="reveal" style={{'--i':i}} key={x}><span>{pad(i+1)}</span><h3>{x}</h3></div>)}</div><p className="bottom-statement reveal" style={{'--i':4}}>Continuous monitoring connects changing conditions to visible, local warnings.</p></>;
case 'objectives':return <div className="objective-list">{[['Integrate','Bring four environmental indicators into one ESP32 system.'],['Validate','Use calibration, filtering, confirmation and recovery.'],['Respond','Assign five risk levels and control warning outputs.'],['Report','Share readings and system states through Blynk.'],['Evaluate','Test normal, abnormal and post-event behavior.']].map(([a,b],i)=><div className="reveal" style={{'--i':i}} key={a}><span>{pad(i+1)}</span><h3>{a}</h3><p>{b}</p></div>)}</div>;
case 'architecture':return <><SignalDiagram/><p className="bottom-statement">Local sensing and warnings continue when the cloud is unavailable.</p></>;
case 'processing':return <><SignalFilter/><div className="editorial-columns">{[['DHT11','Confirm a change','Two consecutive valid readings and separate entry / exit thresholds.'],['MAX4466','Wait for persistence','Quiet-floor calibration and median filtering separate brief sounds from sustained noise.'],['MQ-135','Track the event','Relative baseline ratios and confirmation detect changes. V4.1.6 adds controlled post-event recovery.']].map(([a,b,c],i)=><div className="reveal" style={{'--i':i}} key={a}><span className="eyebrow">{a}</span><h3>{b}</h3><p>{c}</p></div>)}</div></>;
case 'risk':return <><div className="risk-scale">{[['SAFE','No confirmed contribution'],['MONITOR','Mild confirmed warning'],['CAUTION','Score ≥3, unless a higher rule applies'],['HIGH RISK','Two major hazards or a severe-condition rule'],['DANGER','Critical temperature / MQ response, or ≥3 major hazards']].map(([a,b],i)=><div className={'risk-step level-'+(i+1)+' reveal'} key={a} style={{'--i':i}}><span className="risk-number">{i+1}</span><h3>{a}</h3><p>{b}</p><div className="leds" aria-label={`${i+1} cumulative LEDs`}>{[0,1,2,3,4].map(j=><i className={j<=i?'lit':''} key={j}/>)}</div></div>)}</div><p className="footnote">Higher-level rules take precedence. The buzzer uses a separate alarm rule, not the score alone.</p></>;
case 'normal':return <><div className="metrics">{[['26.5','°C','Temperature'],['51','%','Humidity'],['1.00','×','MQ-135 ratio'],['1','','Risk level: SAFE']].map(([a,b,c],i)=><div className="reveal" style={{'--i':i}} key={c}><strong>≈{a}<small>{b}</small></strong><p>{c}</p></div>)}</div><div className="result-line"><b>Risk score 0</b><span>Noise NORMAL</span><span>Only LED 1 on</span><span>Buzzer OFF</span></div><p className="footnote">Recorded representative observation from the IMRAD. These are not live readings.</p></>;
case 'tests':return <div className="test-results">{[['Brief sound','Transient events did not immediately become sustained major hazards.'],['Sustained noise','Persistence progressed into HIGH or VERY HIGH states.'],['High humidity','Approximately 89–91% produced VERY HIGH humidity.'],['Combined conditions','Score ≈6, two major hazards, Level 4 and an active alarm.']].map(([a,b],i)=><div className="reveal" style={{'--i':i}} key={a}><span>{pad(i+1)}</span><h3>{a}</h3><p>{b}</p></div>)}</div>;
case 'recovery':return <><div className="recovery-stages">{[['1.00','Normal'],['1.39','Strong response'],['0.96','Initial recovery'],['1.18–1.25','Rebound']].map(([a,b],i)=><div className="reveal" style={{'--i':i}} key={b}><small>{pad(i+1)} / {b}</small><strong>≈{a}<em>×</em></strong></div>)}</div><div className="finding"><h3>V4.1.6 refinement</h3><p>Track the event peak, confirm a stable decline and cautiously adjust the reference during recovery.</p></div><p className="footnote">The strong-response example used V4.1.5 settings. Final V4.1.6 recovery still needs a regression check.</p></>;
case 'cloud':return <div className="cloud-layout"><img src={dashboard} alt="Actual Blynk dashboard shown in IMRAD Figure 2"/><div><span className="eyebrow">FIGURE 2 / IMRAD</span><h3>One remote view</h3><p>Sensor values, risk level, risk score and alarm status update about every two seconds when online.</p><p className="footnote">This is a documented screenshot. The widget labeled “CPU Temperature” represents DHT11 ambient temperature.</p></div></div>;
case 'limits':return <div className="limits"><div><h3>What the study supports</h3><p>Integrated sensor response, rule-based state transitions, progressive warnings and remote reporting.</p></div><div><h3>What remains outside its scope</h3><p>Certified measurement accuracy, calibrated decibels, exact gas concentration and occupational compliance.</p></div><p className="callout">The final MQ-135 recovery sequence needs a regression check without restarting the device.</p></div>;
case 'conclusion':return <div className="closing"><p className="lead">The prototype demonstrates integrated sensing, automatic warning behavior and supplementary cloud monitoring within an educational scope.</p><button className="primary large" onClick={onDemo}><Icon name="play"/> Continue to the demonstration</button><p className="footnote">Show the actual hardware outputs and the actual Blynk dashboard.</p></div>;
case 'demonstration':return <div className="demo-announcement"><div className="demo-rule" aria-hidden="true"/><p>We will now demonstrate the actual project.</p></div>;
default:return null}}
function Reference(){return <div className="reference-page"><header className="page-heading"><span className="eyebrow">IEEE STYLE</span><h1>Website references</h1></header><ol className="ieee-references">{references.map((r,i)=><li key={r.url} style={{'--i':i}}><span className="citation-number">[{i+1}]</span><div><p>{r.author}, “{r.title},” {r.publication&&<><em>{r.publication}</em>{r.detail?', ':'. '}</>}{r.detail&&<>{r.detail}. </>}{!r.publication&&!r.detail&&'. '}[Online]. Available: <a href={r.url} target="_blank" rel="noreferrer">{r.url}</a></p></div></li>)}</ol></div>}
function AnimatedTitle({text}){return <h1 aria-label={text}>{text.split('\n').map((line,i)=><span className="title-line" key={i} aria-hidden="true">{line.split(' ').map((word,j)=><span className="title-word" key={j} style={{'--word':i*4+j}}>{word}{' '}</span>)}</span>)}</h1>}
function SignalFilter(){return <svg className="filter-motion" viewBox="0 0 800 65" role="img" aria-label="Illustration of filtering a noisy signal into a stable response"><path className="raw-trace" d="M0 33H28L35 12 43 52 51 20 58 40 66 32H99L111 9 123 54 135 19 147 44 158 31H180L190 16 201 48 215 27 230 35H275L289 22 302 42 315 31H347L362 27 378 36 396 32H440"/><path className="clean-trace" d="M450 33H475Q490 33 505 27T535 33T565 33H600Q615 33 630 29T660 33H800"/></svg>}
function App(){const [tab,setTab]=useState('slides'),[index,setIndex]=useState(0),[notes,setNotes]=useState(false),[overview,setOverview]=useState(false),[direction,setDirection]=useState(1),[message,setMessage]=useState(''),[replay,setReplay]=useState(0),[leaving,setLeaving]=useState(false),[motion,setMotion]=useState(()=>!window.matchMedia('(prefers-reduced-motion: reduce)').matches);const transitionTimer=useRef(null);const dialog=useRef(null),gridButton=useRef(null),slide=slides[index];function go(to){const n=Math.max(0,Math.min(slides.length-1,to));if(n===index||transitionTimer.current)return;setDirection(n>=index?1:-1);if(!motion){setIndex(n);return}setLeaving(true);transitionTimer.current=setTimeout(()=>{setIndex(n);setLeaving(false);transitionTimer.current=null},260)}function changeTab(t){clearTimeout(transitionTimer.current);transitionTimer.current=null;setLeaving(false);setTab(t);setOverview(false)}function replayMotion(){if(!motion)setMotion(true);setReplay(r=>r+1)}async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{setMessage('Fullscreen is unavailable here. Try your browser’s fullscreen option.');setTimeout(()=>setMessage(''),5000)}}
useEffect(()=>{const handler=e=>{if(e.target.closest('input,textarea,select,[contenteditable=true]'))return;if(e.key===' '&&e.target.closest('button,a'))return;if(e.key==='Escape'){setOverview(false);return}if(e.key.toLowerCase()==='f'){e.preventDefault();fullscreen();return}if(tab!=='slides')return;if(e.key.toLowerCase()==='r')replayMotion();if(e.key.toLowerCase()==='n')setNotes(n=>!n);if(e.key.toLowerCase()==='g')setOverview(v=>!v);if(overview)return;if(['ArrowRight','PageDown',' '].includes(e.key)){e.preventDefault();go(index+1)}if(['ArrowLeft','PageUp'].includes(e.key)){e.preventDefault();go(index-1)}if(e.key==='Home'){e.preventDefault();go(0)}if(e.key==='End'){e.preventDefault();go(slides.length-1)}};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[index,tab,overview,motion]);
useEffect(()=>()=>clearTimeout(transitionTimer.current),[]);
useEffect(()=>{if(overview){dialog.current.showModal();dialog.current.querySelector('button')?.focus()}else if(dialog.current?.open){dialog.current.close();gridButton.current?.focus()}},[overview]);
return <div className="app" data-motion={motion?'full':'reduced'}><a href="#main" className="skip">Skip to presentation</a><header className="topbar"><a className="brand" href="#" onClick={e=>{e.preventDefault();changeTab('slides');go(0)}} aria-label="Workplace Monitor home"><span className="brand-mark">W<span>·</span></span><span>WORKPLACE<br/><b>MONITOR</b></span></a><nav aria-label="Main navigation">{[['slides','Presentation'],['reference','References']].map(([k,t])=><button key={k} className={tab===k?'selected':''} onClick={()=>changeTab(k)} aria-current={tab===k?'page':undefined}>{t}</button>)}</nav><button className="icon-button fullscreen" title="Fullscreen (F)" aria-label="Toggle fullscreen" onClick={fullscreen}><Icon name="full"/></button></header>
<main id="main" tabIndex="-1">{tab==='slides'?<><div className={'slide slide-'+slide.type+' direction-'+direction+(leaving?' is-leaving':'')} key={slide.id+'-'+replay}><div className="slide-eyebrow"><span>{slide.section}</span><span>{pad(index+1)} / {pad(slides.length)}</span></div><AnimatedTitle text={slide.title}/><div className="slide-content"><SlideContent slide={slide} onDemo={()=>go(slides.length-1)}/></div></div>{notes&&<aside className="speaker-notes"><span className="eyebrow">PRESENTER NOTES · VISIBLE ON THIS SCREEN</span><p>{slide.notes}</p><small>{slide.source}</small></aside>}<footer className="slide-controls"><div className="progress" aria-label={`Slide ${index+1} of ${slides.length}`}><span style={{width:`${(index+1)/slides.length*100}%`}}/></div><div className="controls-row"><div className="control-tools"><button ref={gridButton} className="subtle" onClick={()=>setOverview(true)} title="All slides (G)"><Icon name="grid"/><span>All slides</span></button><button className={'subtle '+(notes?'on':'')} onClick={()=>setNotes(n=>!n)} title="Presenter notes (N)" aria-pressed={notes}><Icon name="note"/><span>Notes</span></button><button className="subtle replay-control" onClick={replayMotion} title="Replay this slide’s animations (R)"><span aria-hidden="true">↻</span><span>Replay</span></button><button className="subtle motion-control" onClick={()=>setMotion(m=>!m)} aria-pressed={motion} title="Enable or reduce motion">Motion {motion?'on':'off'}</button></div><span className="key-hint">← → to navigate <span> / </span> F for fullscreen</span><div className="arrows"><button className="icon-button" aria-label="Previous slide" onClick={()=>go(index-1)} disabled={index===0}><Icon name="prev"/></button><span>{pad(index+1)}<small> / {pad(slides.length)}</small></span><button className="icon-button gold" aria-label="Next slide" onClick={()=>go(index+1)} disabled={index===slides.length-1}><Icon name="next"/></button></div></div></footer></>:<Reference/>}</main>
<dialog ref={dialog} className="overview" onCancel={()=>setOverview(false)} onClick={e=>{if(e.target===e.currentTarget)setOverview(false)}}><div className="overview-head"><h2>Presentation overview</h2><button className="icon-button" aria-label="Close overview" onClick={()=>setOverview(false)}><Icon name="close"/></button></div><div className="overview-grid">{slides.map((s,i)=><button key={s.id} className={i===index?'active':''} onClick={()=>{go(i);setOverview(false)}}><span>{pad(i+1)} / {s.section}</span><strong>{s.title}</strong></button>)}</div></dialog>{message&&<div className="toast" role="status">{message}</div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
